# Generated by Django 4.1.7 on 2023-03-21 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('ciudad', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('Americano', 'Americano'), ('Turca', 'Turca'), ('Italiano', 'Italiano'), ('Oriental', 'Oriental')], max_length=60)),
                ('capacidad', models.IntegerField()),
                ('fecha_fundacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('precio', models.FloatField()),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safaEat.restaurante')),
            ],
        ),
    ]
