# Generated by Django 4.1.7 on 2023-04-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safaEat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
